### ISSUE TITLE
Consider renaming this repo to atom-copy-paste

### ISSUE THREAD

**Issue by rugk** [azat-co/copy-paste#1]
AFAIK it's best practice or maybe also some standard that the atom package repos should start with atom.

**Comment by azat-co** [comment]
@rugk i'm new to atom. the name is not great. auto-paste maybe? or auto-type?

**Comment by rugk** [comment]
Basically my only suggestion was to rename your GitHub repo to "atom-copy-paste".

Obviously you can also rename the package itself. (auto-paste sounds nice, type-demo or something similar would also be possible)

**Comment by rugk** [comment]
:neutral_face:

You did not renamed it so why do you close this issue without any explanation?

**Comment by GeorgeWL** [comment]
Atom package names are always called Atom-[package-name] so they can be more easily found on search.

And tbh I don't really think copy-paste suits the package anyhow, it doesn't describe what it does, something that's got more semantic value might be a good idea like copy-retype or something?

Also yeah, this issue really shouldn't have been closed, even if you don't intend to handle it, it's good practice to only close an issue if solved.
