### ISSUE TITLE
Adds line breaks & autocomplete with CRLF line breaks

### ISSUE THREAD

**Issue by rugk** [azat-co/copy-paste#2]
This package is a great idea. 

It just adds additional lines and adds this `]`:
![copypastedoubleslines](https://cloud.githubusercontent.com/assets/11966684/9857688/44948b56-5b1c-11e5-9b4b-7f720a8f3ab5.gif)

And there's a similar strange behaviour with `\n` in PHP files:
![linebreaksissue](https://cloud.githubusercontent.com/assets/11966684/9857893/a4c4b216-5b1d-11e5-92b7-b0b47fb1c4f9.gif)

(line breaks in test file: CRLF)

**Comment by rugk** [comment]
FYI it seems that the input is important - so if the input string (=the copied text) contains CRLF breaks they it will result in two line breaks written even if the file where you write it to also uses CRLF line endings.

**Comment by azat-co** [comment]
yes, looks like different line endings. I use the same for source and destination so no issues
probably can add a check or replace in the code

also, disable autocomplete, sometimes it adds confusing parens.

**Comment by rugk** [comment]
> also, disable autocomplete, sometimes it adds confusing parens.

Sorry, but I like autocomplete. So I won't disable it for this package.

Or do you mean you want to disable it temporarily when the text is written?
In this case I would do this optional (maybe enabled by default), because maybe the reason you want to record a text entered is that you want to show something with the autocomplete package.

**Comment by azat-co** [comment]
yes, i disable autocomplete temporarily for this package and also when writing text (vs. writing code).

**Comment by azat-co** [comment]
@rugk maybe there's a way to disable autocomplete packages programmatically while using copy-paste, then toggle them back?

**Comment by rugk** [comment]
[**@azat-co**](https://github.com/azat-co) commented on [23. Dez. 2015, 23:01 MEZ](https://github.com/azat-co/copy-paste/issues/2#issuecomment-166999108):

> [@rugk](https://github.com/rugk) maybe there's a way to disable autocomplete packages programmatically while using copy-paste, then toggle them back?

This would be a good thing. At least if it is optional. (opt-out)

**Comment by GilbertMizrahi** [comment]
It works great. However, how can I make the paste to just put one line break instead of two?
