### ISSUE TITLE
Cancel writing?

### ISSUE THREAD

**Issue by rugk** [azat-co/copy-paste#3]
Actually you cannot cancel this writing after you started it.
I think it would be good if you e.g. could just `Esc` and it will stop.

**Comment by azat-co** [comment]
@rugk I listened to you and implemented a stop. You can hit escape or use Menu. Enjoy!

**Comment by azat-co** [comment]
@rugk it's actually v0.4.0 so make sure you update it.

**Comment by rugk** [comment]
:+1:
