### ISSUE TITLE
Cannot close Search and replace panel any more

### ISSUE THREAD

**Issue by rugk** [azat-co/copy-paste#4]
Atom 1.3.2, Windows 7

With all packages disabled and only your package enabled I cannot close the search and replace panel anymore.

Reproduce:
1. Ctrl+F
2. Press Esc

What happens: Nothing.

What should happen: The panel should close.

**Comment by azat-co** [comment]
Yes. I know. Just reload the Atom for now... or submit a pull request with a fix.

**Comment by rugk** [comment]
> Yes. I know.

Okay, a known issue. You should have at least opened an issue about this so that users know this.
It was quite frustrating for me to get out which package was causing this annoying error.
