### ISSUE TITLE
what it looks like?

### ISSUE THREAD

**Issue by zhanglongqi** [azat-co/copy-paste#5]
Could you make a gif or video link so we know how it works clearly?

**Comment by azat-co** [comment]
@zhanglongqi yes I can, but it's not my top priority at the moment

**Comment by GeorgeWL** [comment]
well I think quite a few people aren't keen on touching it until they actually know precisely what it does , maybe a write-up would help then?

**Comment by azat-co** [comment]
@Georgiel you're welcome to submit a PR... honestly, I am that worried that people won't be touching it. I implemented it for myself and it works well... I shared it with other. That's it. It's not my goal to sell others on this package. If people see value and look for it, they'll understand what it's doing or they would at least spend 2 minutes installing and trying it. 
PS: Some people take open source for granted and think the contributors own them and must fix every bug they submit or implement any feature they ask for. I recommend taking pro-active approach instead and submitting PRs.
