### ISSUE TITLE
Consider renaming this repo to atom-copy-paste

### ISSUE THREAD

**Issue by GeorgeWL** [azat-co/copy-paste#6]
It's best Practice to name all packages for Atom with atom-[package-name] as it ensure that it shows easily on the search and it helps developers know that the package is specifically for Atom at a glance, like for example if they were to fork or pull request.

**Comment by azat-co** [comment]
@Georgiel I appreciate your comment. I've seen plenty of packages without atom prefix.

**Comment by GeorgeWL** [comment]
yeah me too, but there do trend to be more with than not.

but tbh, I think it's personal choice in retrospect so I closed the issue myself :smile:
