### ISSUE TITLE
How to edit the speed the delay?

### ISSUE THREAD

**Issue by tweakmy** [azat-co/copy-paste#9]
I couldnt find the settings page for copy-paste? Can shed some light?

**Comment by azat-co** [comment]
@tweakmy in the [baseDelay](https://github.com/azat-co/copy-paste/blob/master/lib/copy-paste.coffee#L48) and [setTimeout](https://github.com/azat-co/copy-paste/blob/master/lib/copy-paste.coffee#L59)
